<div>
    <h2>Здесь будет таймер, который я сделаю в другом задании</h2>
</div>

<div data-bind="scope: 'sAutocomplete'">
<!-- ko template : getTemplate() -->
    <!--/ko-->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "sAutocomplete": {
                        "component": "Amasty_ArtemModule/js/searchAutocomplete",
                        "template": "Amasty_ArtemModule/searchAutocomplete"
                    }
                }
            }
        }
    }
</script>
