<?php
/**
 * @var \Amasty\ArtemModule\Block\Index $block
 */
?>
<div>
    <form method="post" action="<?php $block->getFormAction() ?>">
        <p><input type="text" name="sku"> <br>
            <?php if ($block->getQtyStatus() == 1): ?>
            <input type="number" name="qty" value="<?=$block->getQtyNumber()?>"> <br>
            <?php endif; ?>
        <p><input type="submit"></p>
    </form>
</div>




